global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sales-analytics-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

#remote_write:
#  - url: https://<URL-do-Grafana-Cloud>
#    basic_auth:
#      username: <seu-username>
#      password:<sua-API-key>