apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-analytics-api
  template:
    metadata:
      labels:
        app: sales-analytics-api
    spec:
      containers:
        - name: sales-analytics-api
          image: quay.io/gabriel_piassa/sales_analytics_api:b71a45d4532a504e8ec77286898740415efa2d7f
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10   # tempo para o app subir antes da primeira checagem
            periodSeconds: 10         # frequência de verificação
            timeoutSeconds: 2         # tempo limite para resposta
            failureThreshold: 3       # falhas seguidas antes de reiniciar o container

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: sales-analytics-api
#  annotations:
#    route.openshift.io/termination: edge
#spec:
#  ingressClassName: openshift-default
#  rules:
#    - host: sales-api.a1f857f3c32ae493cb4bb9975e33c20e3-698149660.us-east-2.elb.amazonaws.com
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: sales-analytics-api
#                port:
#                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sales-analytics-api
  namespace: openshift-sales-analytics-api
spec:
  selector:
    app: sales-analytics-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sales-analytics-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sales-analytics-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50    # escala se CPU passar 50%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70    # escala se memória passar 70%