name: Build, Test and Push to Quay.io

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests (Maven)
        run: mvn clean test

      - name: Build Docker Image
        run: docker build -t quay.io/${{ secrets.QUAY_USERNAME }}/meuapp:${{ github.sha }} .

      - name: Login to Quay.io
        run: echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Push Image to Quay.io
        run: docker push quay.io/${{ secrets.QUAY_USERNAME }}/meuapp:${{ github.sha }}
